version: '3.1'
services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - './frontend:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: sh -c "cd /app && yarn install --network-timeout 1000000 && yarn start"
        restart: unless-stopped
    
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app
        ports:
            - 5000:5000
        restart: unless-stopped