version: '3.1'
services:   
    flask:
        container_name: flask
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        ports:
            - 5000:5000
        restart: unless-stopped